server:
  port: 9100
spring:
  cloud:
    nacos:
      discovery:
        metadata:
          env: gray
management:
  endpoints:
    web:
      exposure:
        include: health,info   # 需要暴露的端点
  endpoint:
    health:
      show-details: always     # 方便调试
  server:
  # 如果没特别需要，别单独配端口；保持和应用同端口即可
   port: 9009
