server:
  port: 9002
spring:
  application:
    name: yx-store
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_ADDR:127.0.0.1:8848}
        namespace: public
        metadata:
          env: prd
