server:
  port: 8082

spring:
  application:
    name: yx-store

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus

nacos:
  discovery:
    server-addr: ${NACOS_SERVER:127.0.0.1:8848}
    namespace: ${NACOS_NAMESPACE:public}
    group: ${NACOS_GROUP:DEFAULT_GROUP}
    metadata:
      version: ${SERVICE_VERSION:prd}
